### ISSUE TITLE
Missing documentation to install "ibmcloud oc" plugin

### ISSUE THREAD

**Issue by matthagenbuch** [IBM-Bluemix-Docs/openshift#15]
In section "Lesson 1" part 1, this article includes a link for instructions to install the "ibmcloud oc" CLI plugin [here](https://cloud.ibm.com/docs/containers?topic=containers-cs_cli_install#cs_cli_install_steps).  The linked article does not contain such instructions.

**Comment by Nadine2016** [comment]
@matthagenbuch thanks so much for commenting on the OpenShift documentation. You are right, the link is not correct as we just created a separate OpenShift documentation set and are still linking to the old place. The correct link is https://cloud.ibm.com/docs/openshift?topic=openshift-openshift-cli#cli_oc. I already updated the documentation and it will go out today or latest tomorrow.

**Comment by poojitha-bikki** [comment]
@Nadine2016 I might be missing something here. But, the link you pointed to above is for installing`oc` CLI right. I still couldn't find the docs to get the ibm cloud plugin or `oc` to use commands like `ibmcloud oc cluster-config --cluster <cluster_name_or_ID>`

**Comment by Nadine2016** [comment]
@poojitha-bikki so `ibmcloud oc` is an alias for `ibmcloud ks` so by installing the IBM Cloud Kubernetes Service CLI plug-in, you will be able to use the `ibmcloud oc` commands. 

This would be the link to look at for this installation: https://cloud.ibm.com/docs/openshift?topic=openshift-openshift-cli#cli_ibmcloud_oc

I thought you were looking for the `oc`, such as `oc get pods` commands. 

Let me know if you have more questions about this. 

Thank you

**Comment by poojitha-bikki** [comment]
Thanks for clarifying. I missed the part where it says this : `Kubernetes Service plug-in (ibmcloud oc alias for OpenShift clusters)`.

**Comment by ivandov** [comment]
Since this is a top hit on google for the `ibmcloud oc` plugin install... 

```
ibmcloud plugin install container-service
```
